GET http://localhost:4000/health


###

GET http://localhost:4000


###

POST http://localhost:4000
Content-Type: application/json

{
    "name":"Mushfiq",
    "country":"BD",
    "rank":3
}


###

GET http://localhost:4000/Gtk9ZeR5A


###

GET http://localhost:4000/HNWrLoMrM